name: Build and Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Create deployment archive
      run: |
        cd out
        tar -czf ../deployment.tar.gz .
        cd ..
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Di chuyển đến thư mục project
          cd /home/quangtp/projects/nextjs-app
          
          # Pull code mới
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Build ứng dụng
          npm run build
          
          # Tạo backup
          if [ -d "/var/www/html" ]; then
            sudo cp -r /var/www/html /var/www/html.backup.$(date +%Y%m%d_%H%M%S) || true
          fi
          
          # Deploy files mới
          sudo cp -r out/* /var/www/html/
          
          # Set permissions
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          
          # Reload nginx
          sudo systemctl reload nginx
          
          echo "✅ Deploy completed successfully!"
          
    - name: Upload deployment files
      uses: actions/upload-artifact@v4
      with:
        name: deployment-files
        path: deployment.tar.gz
        
    - name: Cleanup
      run: rm -f deployment.tar.gz
